=== Kenen-Aketsuki/NeverRetreat/GameData/Form/FormData.dtd
<!ELEMENT FormData (Form+)>
<!-- 裁定表 -->
<!ELEMENT Form (Colum+)><!-- 行优先存储 -->
<!ATTLIST Form id ID #REQUIRED><!-- 表名-->

<!ELEMENT Colum (Row+)><!-- 行 -->
<!ATTLIST Colum Key CDATA #REQUIRED><!-- 行号-->

<!ELEMENT Row (#PCDATA)><!-- 列与列内容 -->
<!ATTLIST Row Key CDATA #REQUIRED><!-- 列号-->

=== Kenen-Aketsuki/NeverRetreat/GameData/Form/FireRankForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FormData SYSTEM "FormData.dtd">
<FormData>
    <Form id="FireRankForm">
        <Colum Key="Artillery">
            <Row Key="1">10</Row>
            <Row Key="2">10</Row>
            <Row Key="3">9</Row>
            <Row Key="4">9</Row>
            <Row Key="5">8</Row>
            <Row Key="6">8</Row>
            <Row Key="7">7</Row>
            <Row Key="8">7</Row>
            <Row Key="9">7</Row>
            <Row Key="10">7</Row>
        </Colum>

        <Colum Key="SP-Artillery">
            <Row Key="1">10</Row>
            <Row Key="2">10</Row>
            <Row Key="3">10</Row>
            <Row Key="4">10</Row>
            <Row Key="5">9</Row>
            <Row Key="6">9</Row>
            <Row Key="7">9</Row>
            <Row Key="8">8</Row>
            <Row Key="9">8</Row>
            <Row Key="10">8</Row>
            <Row Key="12">7</Row>
            <Row Key="14">7</Row>
            <Row Key="16">7</Row>
        </Colum>

        <Colum Key="Mortar">
            <Row Key="1">6</Row>
            <Row Key="2">6</Row>
            <Row Key="3">5</Row>
            <Row Key="4">4</Row>
            <Row Key="5">3</Row>
        </Colum>

        <Colum Key="SP-Mortar">
            <Row Key="1">8</Row>
            <Row Key="2">8</Row>
            <Row Key="3">8</Row>
            <Row Key="4">7</Row>
            <Row Key="5">7</Row>
            <Row Key="6">7</Row>
            <Row Key="7">6</Row>
        </Colum>

        <Colum Key="Rocket">
            <Row Key="1">12</Row>
            <Row Key="2">12</Row>
            <Row Key="3">12</Row>
            <Row Key="4">12</Row>
            <Row Key="5">11</Row>
            <Row Key="6">11</Row>
            <Row Key="7">11</Row>
            <Row Key="8">10</Row>
            <Row Key="9">10</Row>
            <Row Key="10">9</Row>
            <Row Key="12">9</Row>
            <Row Key="14">8</Row>
            <Row Key="16">8</Row>
            <Row Key="18">7</Row>
            <Row Key="20">7</Row>
        </Colum>

        <Colum Key="Machine-Grope">
            <Row Key="1">10</Row>
            <Row Key="2">9</Row>
            <Row Key="3">9</Row>
            <Row Key="4">9</Row>
            <Row Key="5">8</Row>
            <Row Key="6">8</Row>
            <Row Key="7">8</Row>
            <Row Key="8">7</Row>
            <Row Key="9">7</Row>
            <Row Key="10">6</Row>
            <Row Key="12">6</Row>
        </Colum>
    </Form>
</FormData>

=== Kenen-Aketsuki/NeverRetreat/GameData/Form/BattleJudgeForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FormData SYSTEM "FormData.dtd">
<!-- 
    战斗裁定表
    行号计算方式： 四舍五入((攻击力/防御力)*2) 若结果大于3，则再除以二向上取整加一
    列号：骰子出数
-->

<FormData>
    <Form id="BattleJudgeForm">
        <Colum Key="0">
            <Row Key="1">2ARR</Row>
            <Row Key="2">2ARR</Row>
            <Row Key="3">1ARR</Row>
            <Row Key="4">1ARR</Row>
            <Row Key="5">ARR</Row>
            <Row Key="6">AR</Row>
            <Row Key="7">X</Row>
            <Row Key="8">X</Row>
        </Colum>

        <Colum Key="1">
            <Row Key="1">1ARR</Row>
            <Row Key="2">1ARR</Row>
            <Row Key="3">AR</Row>
            <Row Key="4">AR</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
            <Row Key="7">DR</Row>
            <Row Key="8">DR</Row>
        </Colum>

        <Colum Key="2">
            <Row Key="1">ARR</Row>
            <Row Key="2">AR</Row>
            <Row Key="3">AR</Row>
            <Row Key="4">X</Row>
            <Row Key="5">X</Row>
            <Row Key="6">DR</Row>
            <Row Key="7">DR</Row>
            <Row Key="8">DRR</Row>
        </Colum>

        <Colum Key="3">
            <Row Key="1">AR</Row>
            <Row Key="2">AR</Row>
            <Row Key="3">X</Row>
            <Row Key="4">X</Row>
            <Row Key="5">DR</Row>
            <Row Key="6">DR</Row>
            <Row Key="7">DRR</Row>
            <Row Key="8">DRR</Row>
        </Colum>

        <Colum Key="4">
            <Row Key="1">AR</Row>
            <Row Key="2">X</Row>
            <Row Key="3">X</Row>
            <Row Key="4">DR</Row>
            <Row Key="5">DR</Row>
            <Row Key="6">DRR</Row>
            <Row Key="7">DRR</Row>
            <Row Key="8">1DRR</Row>
        </Colum>       

        <Colum Key="5">
            <Row Key="1">X</Row>
            <Row Key="2">X</Row>
            <Row Key="3">DR</Row>
            <Row Key="4">DR</Row>
            <Row Key="5">DRR</Row>
            <Row Key="6">DRR</Row>
            <Row Key="7">1DRR</Row>
            <Row Key="8">1DRR</Row>
        </Colum>

        <Colum Key="6">
            <Row Key="1">X</Row>
            <Row Key="2">DR</Row>
            <Row Key="3">DR</Row>
            <Row Key="4">DRR</Row>
            <Row Key="5">DRR</Row>
            <Row Key="6">1DRR</Row>
            <Row Key="7">1DRR</Row>
            <Row Key="8">2DRR</Row>
        </Colum>

        <Colum Key="7">
            <Row Key="1">DR</Row>
            <Row Key="2">DR</Row>
            <Row Key="3">DRR</Row>
            <Row Key="4">DRR</Row>
            <Row Key="5">1DRR</Row>
            <Row Key="6">1DRR</Row>
            <Row Key="7">2DRR</Row>
            <Row Key="8">2DRR</Row>
        </Colum>

        <Colum Key="8">
            <Row Key="1">DR</Row>
            <Row Key="2">DRR</Row>
            <Row Key="3">DRR</Row>
            <Row Key="4">1DRR</Row>
            <Row Key="5">1DRR</Row>
            <Row Key="6">2DRR</Row>
            <Row Key="7">2DRR</Row>
            <Row Key="8">3DRR</Row>
        </Colum>

        <Colum Key="9">
            <Row Key="1">DRR</Row>
            <Row Key="2">DRR</Row>
            <Row Key="3">1DRR</Row>
            <Row Key="4">1DRR</Row>
            <Row Key="5">2DRR</Row>
            <Row Key="6">2DRR</Row>
            <Row Key="7">3DRR</Row>
            <Row Key="8">3DRR</Row>
        </Colum>

        <Colum Key="10">
            <Row Key="1">DRR</Row>
            <Row Key="2">1DRR</Row>
            <Row Key="3">1DRR</Row>
            <Row Key="4">2DRR</Row>
            <Row Key="5">2DRR</Row>
            <Row Key="6">3DRR</Row>
            <Row Key="7">3DRR</Row>
            <Row Key="8">4DRR</Row>
        </Colum>

        <Colum Key="11">
            <Row Key="1">1DRR</Row>
            <Row Key="2">1DRR</Row>
            <Row Key="3">2DRR</Row>
            <Row Key="4">2DRR</Row>
            <Row Key="5">3DRR</Row>
            <Row Key="6">3DRR</Row>
            <Row Key="7">4DRR</Row>
            <Row Key="8">4DRR</Row>
        </Colum>
    </Form>
</FormData>

=== Kenen-Aketsuki/NeverRetreat/GameData/Form/FireStrikeJudgeForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FormData SYSTEM "FormData.dtd">
<!-- 
    火力打击裁定表
-->

<FormData>
    <Form id="FireStrikeJudgeForm">
        <Colum Key="2">
            <Row Key="1">X</Row>
            <Row Key="2">X</Row>
            <Row Key="3">X</Row>
            <Row Key="4">X</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="3">
            <Row Key="1">1D</Row>
            <Row Key="2">1D</Row>
            <Row Key="3">1K</Row>
            <Row Key="4">1K</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="4">
            <Row Key="1">2D</Row>
            <Row Key="2">1D</Row>
            <Row Key="3">1D</Row>
            <Row Key="4">1K</Row>
            <Row Key="5">1K</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="5">
            <Row Key="1">2D</Row>
            <Row Key="2">2D</Row>
            <Row Key="3">1D</Row>
            <Row Key="4">1D</Row>
            <Row Key="5">1K</Row>
            <Row Key="6">1K</Row>
        </Colum>

        <Colum Key="6">
            <Row Key="1">3D</Row>
            <Row Key="2">2D+1K</Row>
            <Row Key="3">2D</Row>
            <Row Key="4">1D+1K</Row>
            <Row Key="5">1D</Row>
            <Row Key="6">1K</Row>
        </Colum>

        <Colum Key="7">
            <Row Key="1">3D</Row>
            <Row Key="2">3D+1K</Row>
            <Row Key="3">2D+1K</Row>
            <Row Key="4">2D+1K</Row>
            <Row Key="5">1D+2K</Row>
            <Row Key="6">1D+2K</Row>
        </Colum>

        <Colum Key="8">
            <Row Key="1">4D+2K</Row>
            <Row Key="2">4D+1K</Row>
            <Row Key="3">3D+2K</Row>
            <Row Key="4">3D+1K</Row>
            <Row Key="5">2D+2K</Row>
            <Row Key="6">2D+2K</Row>
        </Colum>

        <Colum Key="9">
            <Row Key="1">5D+1K</Row>
            <Row Key="2">5D+1K</Row>
            <Row Key="3">4D+1K</Row>
            <Row Key="4">4D+2K</Row>
            <Row Key="5">3D+2K</Row>
            <Row Key="6">3D+2K</Row>
        </Colum>

        <Colum Key="10">
            <Row Key="1">3K</Row>
            <Row Key="2">3K</Row>
            <Row Key="3">5D+2K</Row>
            <Row Key="4">5D+2K</Row>
            <Row Key="5">4D+2K</Row>
            <Row Key="6">4D+2K</Row>
        </Colum>

        <Colum Key="11">
            <Row Key="1">4K</Row>
            <Row Key="2">3K</Row>
            <Row Key="3">3K</Row>
            <Row Key="4">5D+2K</Row>
            <Row Key="5">5D+2K</Row>
            <Row Key="6">4D+3K</Row>
        </Colum>

        <Colum Key="12">
            <Row Key="1">5K</Row>
            <Row Key="2">4K</Row>
            <Row Key="3">3K</Row>
            <Row Key="4">3K</Row>
            <Row Key="5">5D+3K</Row>
            <Row Key="6">4D+3K</Row>
        </Colum>
    </Form>
</FormData>

=== Kenen-Aketsuki/NeverRetreat/GameData/Form/AirBattleJudgeForm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FormData SYSTEM "FormData.dtd">
<!-- 
    空战裁定表
-->
<FormData>
    <Form id="AirBattleJudgeForm">
        <Colum Key="0">
            <Row Key="1">X</Row>
            <Row Key="2">X</Row>
            <Row Key="3">X</Row>
            <Row Key="4">X</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="1">
            <Row Key="1">1D</Row>
            <Row Key="2">1D</Row>
            <Row Key="3">X</Row>
            <Row Key="4">X</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="2">
            <Row Key="1">2D</Row>
            <Row Key="2">1D</Row>
            <Row Key="3">1D</Row>
            <Row Key="4">X</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="3">
            <Row Key="1">2D</Row>
            <Row Key="2">2D</Row>
            <Row Key="3">1D</Row>
            <Row Key="4">1D</Row>
            <Row Key="5">X</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="4">
            <Row Key="1">C</Row>
            <Row Key="2">2D</Row>
            <Row Key="3">2D</Row>
            <Row Key="4">1D</Row>
            <Row Key="5">1D</Row>
            <Row Key="6">X</Row>
        </Colum>

        <Colum Key="5">
            <Row Key="1">C</Row>
            <Row Key="2">C</Row>
            <Row Key="3">2D</Row>
            <Row Key="4">2D</Row>
            <Row Key="5">1D</Row>
            <Row Key="6">1D</Row>
        </Colum>

        <Colum Key="6">
            <Row Key="1">C</Row>
            <Row Key="2">C</Row>
            <Row Key="3">C</Row>
            <Row Key="4">2D</Row>
            <Row Key="5">2D</Row>
            <Row Key="6">1D</Row>
        </Colum>
    </Form>
</FormData>
