=== Kenen-Aketsuki/NeverRetreat/GameData/Piece/PieceData.dtd
<!-- 这里记述兵种的信息，包括兵种的战斗力等信息 -->
<!ELEMENT PieceInfo (Piece+)>

<!ELEMENT Piece (name,Datas,ability,enterForbidden?)>
<!ATTLIST Piece isAir (True|False) "False"><!-- 是否为空中单位 -->
<!ATTLIST Piece id ID #REQUIRED>

<!ELEMENT name (#PCDATA)><!-- 棋子名称 -->
<!ELEMENT Datas (ATK,cATK?,DEF,cDEF?,MOV,cMOV?,activeArea?,passiveArea?)><!-- 棋子数据 -->
<!-- 任意值小于零代表其无法执行对应能力-->
<!ELEMENT ATK (#PCDATA)>
<!ELEMENT DEF (#PCDATA)>
<!ELEMENT MOV (#PCDATA)>
<!ELEMENT cDEF (#PCDATA)>
<!ELEMENT cATK (#PCDATA)>
<!ELEMENT cMOV (#PCDATA)>
<!ELEMENT activeArea (#PCDATA)>
<!ELEMENT passiveArea (#PCDATA)>

<!ELEMENT ability EMPTY><!-- 棋子的能力 -->
<!ATTLIST ability canSupport (True|False) #REQUIRED>
<!ATTLIST ability canAirBattle (True|False) #REQUIRED>
<!ATTLIST ability canDoMagic (True|False) #IMPLIED>
<!ATTLIST ability canFixMod (True|False) #IMPLIED>
<!ATTLIST ability canBild (True|False) #IMPLIED>
<!ATTLIST ability canMental (True|False) #IMPLIED>

<!ELEMENT enterForbidden (forbidFix+)><!-- 准入限制，不填默遵循规则限制,准入优先级遵循：特殊地形>临时设施=固定设施>基础地形，即以最高优先级地形的准入为准-->
<!ELEMENT forbidFix EMPTY>
<!ATTLIST forbidFix fixWay (ADD|MULTY|NOPE|ALL) #REQUIRED>
<!ATTLIST forbidFix fixNumber CDATA #REQUIRED>

=== Kenen-Aketsuki/NeverRetreat/GameData/Piece/ModCrash_Piece.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PieceInfo SYSTEM "PieceData.dtd">
<PieceInfo>
    <Piece id="Blade">
        <name>冷兵种</name>
        <Datas>
            <ATK>4</ATK>
            <DEF>4</DEF>
            <MOV>6</MOV>
            <crashLoad>1</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" />
    </Piece>
    
    <Piece id="Gunner">
        <name>火器种</name>
        <Datas>
            <ATK>4</ATK>
            <DEF>4</DEF>
            <MOV>6</MOV>
            <cATK>2</cATK>
            <cDEF>2</cDEF>
            <cMOV>3</cMOV>
            <crashLoad>1</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" />
    </Piece>

    <Piece id="Heavy-Gunner">
        <name>重型火器种</name>
        <Datas>
            <ATK>6</ATK>
            <DEF>6</DEF>
            <MOV>10</MOV>
            <cATK>3</cATK>
            <cDEF>3</cDEF>
            <cMOV>5</cMOV>
            <crashLoad>2</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" />
    </Piece>

    <Piece id="Machine-Grope">
        <name>机械集群</name>
        <Datas>
            <ATK>6</ATK>
            <DEF>6</DEF>
            <MOV>10</MOV>
            <cATK>3</cATK>
            <cDEF>3</cDEF>
            <cMOV>5</cMOV>
            <activeArea>12</activeArea>
            <crashLoad>2</crashLoad>
        </Datas>
        <ability canSupport="True" canAirBattle="False" />
    </Piece>

    <Piece id="Warlock">
        <name>诡术种</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>3</DEF>
            <MOV>5</MOV>
            <cATK>-1</cATK>
            <cDEF>1</cDEF>
            <cMOV>5</cMOV>
            <crashLoad>3</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" canDoMagic="True"/>
    </Piece>

    <Piece id="Hacker">
        <name>扰动者</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>-1</DEF>
            <MOV>5</MOV>
            <passiveArea>3</passiveArea>
            <crashLoad>3</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" canFixMod="True"/>
    </Piece>

    <Piece id="Inciter">
        <name>煽动者</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>-1</DEF>
            <MOV>6</MOV>
            <crashLoad>3</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" canMental="True"/>
    </Piece>

    <Piece id="Soar-Net" isAir="True">
        <name>空网</name>
        <Datas>
            <ATK>2</ATK>
            <DEF>5</DEF>
            <MOV>-1</MOV>
            <activeArea>5</activeArea>
            <crashLoad>4</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" canFixMod="True"/>
    </Piece>

    <Piece id="Soar-Stay" isAir="True">
        <name>滞空种</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>5</DEF>
            <MOV>-1</MOV>
            <crashLoad>2</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="True"/>
    </Piece>

    <Piece id="Soar-Attack" isAir="True">
        <name>袭略种</name>
        <Datas>
            <ATK>8</ATK>
            <DEF>3</DEF>
            <MOV>-1</MOV>
            <crashLoad>2</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False"/>
    </Piece>

    <Piece id="Infantry-Betray">
        <name>被蛊惑者</name>
        <Datas>
            <ATK>4</ATK>
            <DEF>4</DEF>
            <MOV>5</MOV>
            <crashLoad>0</crashLoad>
        </Datas>
        <ability canSupport="False" canAirBattle="False" canFixMod="False"/>
    </Piece>
</PieceInfo>

=== Kenen-Aketsuki/NeverRetreat/GameData/Piece/HumanPiece.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PieceInfo SYSTEM "PieceData.dtd">
<PieceInfo>
    <Piece id="Infantry-Army">
        <name>步兵连-正规军</name>
        <Datas>
            <ATK>4</ATK>
            <DEF>4</DEF>
            <MOV>5</MOV>
            <cATK>2</cATK>
            <cDEF>2</cDEF>
            <cMOV>3</cMOV>
        </Datas>
        <ability canSupport="False" canAirBattle="False" />
    </Piece>

    <Piece id="Infantry-GovGuard">
        <name>步兵连-政府近卫军</name>
        <Datas>
            <ATK>3</ATK>
            <DEF>3</DEF>
            <MOV>5</MOV>
            <cATK>1</cATK>
            <cDEF>1</cDEF>
            <cMOV>3</cMOV>
        </Datas>
        <ability canSupport="False" canAirBattle="False" />
    </Piece>

    <Piece id="MachineInfantry">
        <name>机械化步兵连</name>
        <Datas>
            <ATK>6</ATK>
            <DEF>4</DEF>
            <MOV>10</MOV>
            <cATK>3</cATK>
            <cDEF>2</cDEF>
            <cMOV>4</cMOV>
        </Datas>
        <ability canSupport="False" canAirBattle="False" />
    </Piece>

    <Piece id="Mortar">
        <name>迫击炮排</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>2</DEF>
            <MOV>5</MOV>
            <cATK>-1</cATK>
            <cDEF>1</cDEF>
            <cMOV>3</cMOV>
            <activeArea>5</activeArea>
        </Datas>
        <ability canSupport="True" canAirBattle="False" />
    </Piece>

    <Piece id="SP-Mortar">
        <name>自行迫击炮连</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>3</DEF>
            <MOV>10</MOV>
            <cATK>-1</cATK>
            <cDEF>2</cDEF>
            <cMOV>4</cMOV>
            <activeArea>7</activeArea>
        </Datas>
        <ability canSupport="True" canAirBattle="False" />
    </Piece>

    <Piece id="Artillery">
        <name>炮兵连</name>
        <Datas>
            <ATK>3</ATK>
            <DEF>5</DEF>
            <MOV>5</MOV>
            <cATK>1</cATK>
            <cDEF>3</cDEF>
            <cMOV>3</cMOV>
            <activeArea>10</activeArea>
        </Datas>
        <ability canSupport="True" canAirBattle="True" />
    </Piece>

    <Piece id="Engineer">
        <name>工兵连</name>
        <Datas>
            <ATK>-1</ATK>
            <DEF>3</DEF>
            <MOV>5</MOV>
            <cATK>-1</cATK>
            <cDEF>1</cDEF>
            <cMOV>2</cMOV>
        </Datas>
        <ability canSupport="False" canAirBattle="False" canBild="True"/>
    </Piece>

    <Piece id="Anti-Aircraft">
        <name>防空连</name>
        <Datas>
            <ATK>5</ATK>
            <DEF>5</DEF>
            <MOV>3</MOV>
            <cATK>5</cATK>
            <cDEF>3</cDEF>
            <cMOV>2</cMOV>
            <activeArea>4</activeArea>
        </Datas>
        <ability canSupport="False" canAirBattle="True" />
    </Piece>
</PieceInfo>
