=== Kenen-Aketsuki/NeverRetreat/GameData/StartState/TurnData.dtd
<!ELEMENT TurnData (Turn+,BegianSupportList)>
<!ELEMENT Turn (MaxActiveBarrierAmmount,MaxActiveFissureAmmount,CrashBundith,reinforceList-Human?,reinforceList-Crash?,StartStage?,MobilizationRate?,TrainedTroopMount?)>
<!ATTLIST Turn No CDATA #REQUIRED><!-- 回合编号-->
<!ATTLIST Turn Allow (Human|Crash|Both) #IMPLIED><!-- 本回合允许行动，不填默认未Both-->
<!ATTLIST Turn isSave (True|False) #IMPLIED><!-- 是否为存档，默认为false-->
<!ATTLIST Turn startFrom (Human|Crash) #IMPLIED><!-- 起始方，默认为Crash-->

<!ELEMENT MaxActiveBarrierAmmount (#PCDATA)><!-- 最大安定节点激活数 -->
<!ELEMENT MaxActiveFissureAmmount (#PCDATA)><!-- 最大次元裂隙激活数 -->
<!ELEMENT reinforceList-Human (Reinforce+)><!-- 人类援助 -->
<!ELEMENT reinforceList-Crash (Reinforce+)><!-- 崩溃援助 -->

<!ELEMENT Reinforce EMPTY>
<!ATTLIST Reinforce TroopName CDATA #REQUIRED><!-- 部队番号 -->
<!ATTLIST Reinforce EnterPlace CDATA #REQUIRED><!-- 部队入场位置 -->
<!ATTLIST Reinforce ResTurn CDATA #IMPLIED><!-- 剩余回合数，不写默认本回合入场 -->

<!ELEMENT StartStage (#PCDATA)><!-- 执行列表，不填则从Strategy阶段开始顺序执行-->

<!ELEMENT CrashBundith (#PCDATA)><!-- 崩坏带宽 -->
<!ELEMENT MobilizationRate (#PCDATA)><!-- 当前动员率-->
<!ELEMENT TrainedTroopMount (#PCDATA)><!-- 预备役数量 -->

<!ELEMENT BegianSupportList (HumanList,CrashList)><!-- 双方的支援签列表 -->
<!ELEMENT HumanList (Item+)><!-- 人类方列表-->
<!ELEMENT CrashList (Item+)><!-- 崩坏方列表-->
<!ELEMENT Item EMPTY><!-- 支援签项 -->
<!ATTLIST Item TroopName ID #REQUIRED><!-- 部队番号 -->
<!ATTLIST Item UseableTime CDATA #REQUIRED><!-- 可用次数-->

=== Kenen-Aketsuki/NeverRetreat/GameData/StartState/Turns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TurnData SYSTEM "TurnData.dtd">
<TurnData>
    <Turn No="0" Allow="Human">
        <MaxActiveBarrierAmmount>0</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>0</MaxActiveFissureAmmount>
        <CrashBundith>114514</CrashBundith>
        <StartStage>ZeroTurn</StartStage>
        <MobilizationRate>50</MobilizationRate>
        <TrainedTroopMount>10</TrainedTroopMount>
    </Turn>
    <Turn No="1" Allow="Both">
        <MaxActiveBarrierAmmount>3</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>1</MaxActiveFissureAmmount>
        <CrashBundith>150</CrashBundith>
        <reinforceList-Human>
            <Reinforce TroopName="DawIV.101" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.102" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.103" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.111" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.112" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.113" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.121" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.122" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.123" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.101P" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.102P" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.s01E" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.s02E" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.101Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.102Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.103Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.111Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.112Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.113Pz" EnterPlace="Airpot"/>
        </reinforceList-Human>
    </Turn>
    <Turn No="2">
        <MaxActiveBarrierAmmount>3</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>2</MaxActiveFissureAmmount>
        <CrashBundith>150</CrashBundith>
        <reinforceList-Human>
            <Reinforce TroopName="DawIV.201" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.202" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.203" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.211" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.212" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.213" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.221" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.222" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.223" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.201P" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.202P" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.s01M" EnterPlace="Airpot"/>
            <Reinforce TroopName="DawIV.s02M" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.201Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.202Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.203Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.211Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.212Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.213Pz" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.101AAA" EnterPlace="Airpot"/>  
            <Reinforce TroopName="ForDII.102AAA" EnterPlace="Airpot"/>  
            <Reinforce TroopName="ForDII.103AAA" EnterPlace="Airpot"/>
        </reinforceList-Human>
    </Turn>
    <Turn No="3">
        <MaxActiveBarrierAmmount>2</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>3</MaxActiveFissureAmmount>
        <CrashBundith>150</CrashBundith>
        <reinforceList-Human>
            <Reinforce TroopName="DawIV.s1AA" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.s2AA" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.s01Art" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.s02Art" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.s03Art" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.301" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.302" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.303" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.311" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.312" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.313" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.321" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.322" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.323" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.301P" EnterPlace="Airpot"/>  
            <Reinforce TroopName="DawIV.302P" EnterPlace="Airpot"/>
            <Reinforce TroopName="ForDII.101SPA" EnterPlace="Airpot"/>  
            <Reinforce TroopName="ForDII.102SPA" EnterPlace="Airpot"/>  
            <Reinforce TroopName="ForDII.103SPA" EnterPlace="Airpot"/>
        </reinforceList-Human>
    </Turn>
    <Turn No="4">
        <MaxActiveBarrierAmmount>2</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>4</MaxActiveFissureAmmount>
        <CrashBundith>170</CrashBundith>
        <reinforceList-Human>
            <Reinforce TroopName="ForDII.101Rok" EnterPlace="Airpot" />  
            <Reinforce TroopName="ForDII.102Rok" EnterPlace="Airpot" />
            <Reinforce TroopName="ForDII.103Rok" EnterPlace="Airpot" />
            <Reinforce TroopName="DawIV.101v" EnterPlace="Button-21" />
            <Reinforce TroopName="DawIV.102v" EnterPlace="Button-21" />
            <Reinforce TroopName="DawIV.103v" EnterPlace="Button-21" />
            <Reinforce TroopName="DawIV.104vP" EnterPlace="Button-21"/>
            <Reinforce TroopName="DawIV.201v" EnterPlace="Button-21" />
            <Reinforce TroopName="DawIV.202v" EnterPlace="Button-21" />
            <Reinforce TroopName="DawIV.203v" EnterPlace="Button-21" />
            <Reinforce TroopName="DawIV.204vP" EnterPlace="Button-21" />
        </reinforceList-Human>
    </Turn>
    <Turn No="5">
        <MaxActiveBarrierAmmount>1</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>4</MaxActiveFissureAmmount>
        <CrashBundith>170</CrashBundith>
        <reinforceList-Human>
            <Reinforce TroopName="LRV41.Mx11" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Mx12" EnterPlace="Top-16" />
            <Reinforce TroopName="LRV41.Mx13" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Mx21" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Mx22" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Mx23" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Tk11" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Tk12" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.Tk13" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.SPA1" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.SPA2" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.AME1" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.AME2" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.AME3" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.EME1" EnterPlace="Top-16" />  
            <Reinforce TroopName="LRV41.EME2" EnterPlace="Top-16" />
        </reinforceList-Human>
    </Turn>
    <Turn No="6">
        <MaxActiveBarrierAmmount>1</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>4</MaxActiveFissureAmmount>
        <CrashBundith>170</CrashBundith>
    </Turn>
    <Turn No="7">
        <MaxActiveBarrierAmmount>0</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>5</MaxActiveFissureAmmount>
        <CrashBundith>200</CrashBundith>
    </Turn>
    <Turn No="8">
        <MaxActiveBarrierAmmount>0</MaxActiveBarrierAmmount>
        <MaxActiveFissureAmmount>5</MaxActiveFissureAmmount>
        <CrashBundith>200</CrashBundith>
    </Turn>

    <BegianSupportList>
        <HumanList>
            <Item TroopName="RiseSun.AtkAir" UseableTime="0" />
            <Item TroopName="RiseSun.Bomer" UseableTime="0" />
            <Item TroopName="RiseSun.Fight" UseableTime="0" />
            <Item TroopName="RiseSun.UAV" UseableTime="0" />
        </HumanList>
        <CrashList>
            <Item TroopName="Crash.SNet" UseableTime="0" />
            <Item TroopName="Crash.SStay" UseableTime="3" />
            <Item TroopName="Crash.GAtk" UseableTime="3" />
        </CrashList>
    </BegianSupportList>

</TurnData>
